#server:
#  port: 8089
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/motorinsurance
#    username: root
#    password: root

#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#application:
#  name: MotarInsurance-SERVICE
#config:
#  import: optional:configserver:http://localhost:8080

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
      name: MOTOR-INSURANCE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/motorinsurance?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Root@123
  cloud:
    config:
      import-check:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    hostname: localhost

#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  application:
#    name: Motar-Insurance-SERVICE



#config:
#  import: optional:configserver:http://localhost:8089


